// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8KKLjUk0ABLqwjwddXS2pds2TCRC1LMM',
    appId: '1:872569464115:web:dd3643a81c9efd91314a46',
    messagingSenderId: '872569464115',
    projectId: 'fluttertodo-b4ac7',
    authDomain: 'fluttertodo-b4ac7.firebaseapp.com',
    storageBucket: 'fluttertodo-b4ac7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYR1DFXmXPg-oyhIsWRStWhtj7n7g3WeY',
    appId: '1:872569464115:android:288adc738af6c6e8314a46',
    messagingSenderId: '872569464115',
    projectId: 'fluttertodo-b4ac7',
    storageBucket: 'fluttertodo-b4ac7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwjO4DP0P8rOiPY3LZe5_2v-eYNHzYYUI',
    appId: '1:872569464115:ios:161ad1ad573a84d4314a46',
    messagingSenderId: '872569464115',
    projectId: 'fluttertodo-b4ac7',
    storageBucket: 'fluttertodo-b4ac7.appspot.com',
    iosBundleId: 'com.swarthyPig.ddudu',
  );
}
